version: '3.8'
services:
  localstack:    
    image: localstack/localstack:latest
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DATA_DIR: /tmp/localstack/data
    ports:
      - '4566:4566'  # LocalStack Gateway
    volumes:            
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack-setup.sh:/etc/localstack/init/ready.d/script.sh'

volumes:
  pgdata: